"""Static registry of all market metric definitions (data only).

This module holds the _METRICS and _CONCEPTUAL_METRICS lists plus the
pure helper functions used by both UnifiedMetricCatalog and
StaticMarketMetricCatalog. Extracting the data here lets the unified
catalog import it without pulling in the old class.
"""

from finbar_strategy_runtime.domain.entities.data_class import DataClass
from finbar_strategy_runtime.domain.entities.market_metric_definition import (
    MarketMetricDefinition,
)
from finbar_strategy_runtime.domain.entities.metric_confidence import MetricConfidence
from finbar_strategy_runtime.domain.entities.metric_family import MetricFamily
from finbar_strategy_runtime.domain.entities.metric_resolution_path import (
    MetricResolutionPath,
)



# ====================================================================
# Helper functions
# ====================================================================

def _is_class_available(
    required: tuple[DataClass, ...], available: DataClass
) -> bool:
    """Return True when `available` satisfies any of the `required` classes."""
    if not required:
        return True
    return available in required


def _interval_matches(available: str, required_min: str) -> bool:
    """Check whether the available interval is at least as fine as required.

    For intraday data, '5min' is finer than '1h'.
    For daily, only '1d' or '' matches.
    """
    if not required_min:
        return True

    def _to_minutes(interval: str) -> int:
        if interval in ("1d", "", "day"):
            return 1440
        if interval.endswith("min"):
            return int(interval.replace("min", ""))
        if interval.endswith("h"):
            return int(interval.replace("h", "")) * 60
        return 0

    return _to_minutes(available) <= _to_minutes(required_min)




METRICS: list[MarketMetricDefinition] = [
    # --- Spread proxies (7) ---
    MarketMetricDefinition(
        name="corwin_schultz_spread",
        family=MetricFamily.SPREAD,
        description="OHLC-based bid-ask spread estimator with overnight-gap adjustment.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Corwin & Schultz (2012), 'A Simple Way to Estimate Bid-Ask Spreads'",
    ),
    MarketMetricDefinition(
        name="roll_spread",
        family=MetricFamily.SPREAD,
        description="Serial covariance spread estimator (close-to-close).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Roll (1984), 'A Simple Implicit Measure of the Effective Bid-Ask Spread'",
    ),
    MarketMetricDefinition(
        name="abdi_ranaldo_spread",
        family=MetricFamily.SPREAD,
        description="OHLC-based spread estimator using mid-price and close.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Abdi & Ranaldo (2017), 'A Simple Estimation of Bid-Ask Spreads'",
    ),
    MarketMetricDefinition(
        name="effective_tick_spread",
        family=MetricFamily.SPREAD,
        description="Tick-based spread estimator using close-to-close price clustering.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=60,
        confidence=MetricConfidence.PROXY,
        paper_reference="Holden (2009), 'New Low-Frequency Spread Measures'",
    ),
    MarketMetricDefinition(
        name="fong_holden_tran_spread",
        family=MetricFamily.SPREAD,
        description="FHT simple spread estimator using OHLC.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Fong, Holden & Trzcinka (2017), 'What Are the Best Liquidity Proxies?'",
    ),
    MarketMetricDefinition(
        name="chung_zhang_spread",
        family=MetricFamily.SPREAD,
        description="OHLC-based spread estimator with simple calculation.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Chung & Zhang (2014), 'A Simple Approximation of Intraday Spreads'",
    ),
    MarketMetricDefinition(
        name="lot_zero_return_spread",
        family=MetricFamily.SPREAD,
        description="LOT spread from zero-return proportion.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=60,
        confidence=MetricConfidence.PROXY,
        paper_reference="Lesmond, Ogden & Trzcinka (1999), 'A New Estimate of Transaction Costs'",
    ),

    # --- Volatility (9) ---
    MarketMetricDefinition(
        name="close_to_close_vol",
        family=MetricFamily.VOLATILITY,
        description="Naive close-to-close return volatility.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=20,
        confidence=MetricConfidence.ACTUAL,
    ),
    MarketMetricDefinition(
        name="parkinson_vol",
        family=MetricFamily.VOLATILITY,
        description="Parkinson high-low range volatility estimator.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Parkinson (1980), 'The Extreme Value Method for Estimating Variance'",
    ),
    MarketMetricDefinition(
        name="garman_klass_vol",
        family=MetricFamily.VOLATILITY,
        description="Garman-Klass OHLC volatility estimator.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Garman & Klass (1980), 'On the Estimation of Security Price Volatilities'",
    ),
    MarketMetricDefinition(
        name="rogers_satchell_vol",
        family=MetricFamily.VOLATILITY,
        description="Rogers-Satchell OHLC volatility estimator (drift-independent).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Rogers & Satchell (1991), 'Estimating Variance from High, Low and Closing Prices'",
    ),
    MarketMetricDefinition(
        name="yang_zhang_vol",
        family=MetricFamily.VOLATILITY,
        description="Yang-Zhang OHLC volatility estimator with overnight gap adjustment.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=21,
        confidence=MetricConfidence.PROXY,
        paper_reference="Yang & Zhang (2000), 'Drift-Independent Volatility Estimation'",
    ),
    MarketMetricDefinition(
        name="gk_plus_overnight_vol",
        family=MetricFamily.VOLATILITY,
        description="Garman-Klass with overnight gap component.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="meilijson_vol",
        family=MetricFamily.VOLATILITY,
        description="Meilijson OHLC volatility estimator.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Meilijson (2009), 'A Simple, Fast and Accurate Nonparametric Estimator'",
    ),
    MarketMetricDefinition(
        name="daily_return_skewness",
        family=MetricFamily.VOLATILITY,
        description="Rolling skewness of daily returns.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=60,
        confidence=MetricConfidence.ACTUAL,
    ),
    MarketMetricDefinition(
        name="daily_return_kurtosis",
        family=MetricFamily.VOLATILITY,
        description="Rolling kurtosis of daily returns.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=60,
        confidence=MetricConfidence.ACTUAL,
    ),

    # --- Liquidity / impact (8) ---
    MarketMetricDefinition(
        name="amihud_illiq",
        family=MetricFamily.LIQUIDITY_IMPACT,
        description="Amihud illiquidity measure: |return| / dollar_volume.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Amihud (2002), 'Illiquidity and Stock Returns'",
    ),
    MarketMetricDefinition(
        name="amivest_liquidity",
        family=MetricFamily.LIQUIDITY_IMPACT,
        description="Inverse Amihud — dollar volume per unit price change.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="florackis_lambda",
        family=MetricFamily.LIQUIDITY_IMPACT,
        description="Return-to-volume ratio liquidity measure.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Florackis, Gregoriou & Kostakis (2011), 'Trading Frequency and Asset Pricing'",
    ),
    MarketMetricDefinition(
        name="hasbrouck_daily_lambda",
        family=MetricFamily.LIQUIDITY_IMPACT,
        description="Daily price impact proxy from Hasbrouck.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Hasbrouck (2009), 'Trading Costs and Returns for US Equities'",
    ),
    MarketMetricDefinition(
        name="liu_illiq",
        family=MetricFamily.LIQUIDITY_IMPACT,
        description="Liu illiquidity: days-with-zero-volume proportion.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("volume",),
        min_lookback=21,
        confidence=MetricConfidence.PROXY,
        paper_reference="Liu (2006), 'A Liquidity-Augmented Capital Asset Pricing Model'",
    ),
    MarketMetricDefinition(
        name="bao_pan_zhou_cost",
        family=MetricFamily.LIQUIDITY_IMPACT,
        description="Trading cost proxy from close-to-close return reversal.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Bao, Pan & Zhou (2011), 'The Volcker Rule and Market-Making in Times of Stress'",
    ),

    # --- Order flow proxies (6) ---
    MarketMetricDefinition(
        name="signed_sqrt_volume_ofi",
        family=MetricFamily.ORDER_FLOW,
        description="Signed square-root volume order flow imbalance proxy.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="cumulative_signed_volume_ofi",
        family=MetricFamily.ORDER_FLOW,
        description="Cumulative signed volume OFI from BVC classification.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="bvc_buy_volume",
        family=MetricFamily.ORDER_FLOW,
        description="Bulk volume classification estimated buy volume.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="bvc_sell_volume",
        family=MetricFamily.ORDER_FLOW,
        description="Bulk volume classification estimated sell volume.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="bvc_ofi",
        family=MetricFamily.ORDER_FLOW,
        description="Order flow imbalance from bulk volume classification.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="return_volume_correlation",
        family=MetricFamily.ORDER_FLOW,
        description="Rolling correlation between returns and volume.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),

    # --- Informed trading proxies (2) ---
    MarketMetricDefinition(
        name="daily_vpin",
        family=MetricFamily.INFORMED_TRADING,
        description="Daily volume-synchronized probability of informed trading.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=50,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="spread_based_pin_proxy",
        family=MetricFamily.INFORMED_TRADING,
        description="PIN proxy estimated from spread-based metrics.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),

    # --- Jump risk proxies (4) ---
    MarketMetricDefinition(
        name="jump_gap_proxy",
        family=MetricFamily.JUMP_TAIL_RISK,
        description="Jump detection from overnight gap in OHLC bars.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="extreme_return_flag",
        family=MetricFamily.JUMP_TAIL_RISK,
        description="Binary flag for extreme returns exceeding a threshold.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="cc_rs_jump_proxy",
        family=MetricFamily.JUMP_TAIL_RISK,
        description="Close-to-close / range-based jump detection proxy.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="overnight_gap_proxy",
        family=MetricFamily.JUMP_TAIL_RISK,
        description="Overnight gap as a jump risk indicator.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),

    # --- Resiliency proxies (3) ---
    MarketMetricDefinition(
        name="resiliency_autocorr",
        family=MetricFamily.RESILIENCY,
        description="Market resiliency via return autocorrelation.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="resiliency_spread_to_impact",
        family=MetricFamily.RESILIENCY,
        description="Resiliency from spread-to-price-impact ratio.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="inverse_amihud_resiliency",
        family=MetricFamily.RESILIENCY,
        description="Resiliency from inverse Amihud illiquidity.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),

    # --- Intraday seasonality proxies (4) ---
    MarketMetricDefinition(
        name="overnight_return",
        family=MetricFamily.INTRADAY_SEASONALITY,
        description="Overnight return component from OHLC decomposition.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=1,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="intraday_return",
        family=MetricFamily.INTRADAY_SEASONALITY,
        description="Intraday return component from OHLC decomposition.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=1,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="parametric_u_shape",
        family=MetricFamily.INTRADAY_SEASONALITY,
        description="Parametric U-shaped intraday volume curve proxy.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("volume",),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="first_last_hour_vol_fraction",
        family=MetricFamily.INTRADAY_SEASONALITY,
        description="Fraction of volume in first and last hours.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),

    # --- Order arrival proxies (2) ---
    MarketMetricDefinition(
        name="volume_to_trade_count_proxy",
        family=MetricFamily.ORDER_ARRIVAL,
        description="Volume divided by trade count proxy.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("volume",),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="trade_count_daily",
        family=MetricFamily.ORDER_ARRIVAL,
        description="Daily trade count from tick-level data.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("trade_count",),
        min_lookback=1,
        confidence=MetricConfidence.PROXY,
    ),

    # --- Intraday OHLCV metrics (implementable, handler backlog) ---
    MarketMetricDefinition(
        name="realized_vol_5m",
        family=MetricFamily.VOLATILITY,
        description="Realized volatility from 5-min returns.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=78,  # ~1 day of 5-min bars
        confidence=MetricConfidence.UNAVAILABLE,
        implemented=False,
        proxy_candidates=("yang_zhang_vol", "parkinson_vol"),
    ),
    MarketMetricDefinition(
        name="realized_vol_15m",
        family=MetricFamily.VOLATILITY,
        description="Realized volatility from 15-min returns.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=26,
        confidence=MetricConfidence.UNAVAILABLE,
        implemented=False,
        proxy_candidates=("yang_zhang_vol", "parkinson_vol"),
    ),
    MarketMetricDefinition(
        name="realized_vol_1h",
        family=MetricFamily.VOLATILITY,
        description="Realized volatility from 1-hour returns.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=7,
        confidence=MetricConfidence.UNAVAILABLE,
        implemented=False,
        proxy_candidates=("yang_zhang_vol", "garman_klass_vol"),
    ),
    MarketMetricDefinition(
        name="bipower_variation",
        family=MetricFamily.VOLATILITY,
        description="Bipower variation for jump-robust volatility from intraday returns.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=78,
        confidence=MetricConfidence.UNAVAILABLE,
        implemented=False,
        proxy_candidates=("cc_rs_jump_proxy",),
        paper_reference="Barndorff-Nielsen & Shephard (2004), 'Power and Bipower Variation'",
    ),
    MarketMetricDefinition(
        name="realized_skewness",
        family=MetricFamily.VOLATILITY,
        description="Skewness of intraday returns.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=78,
        confidence=MetricConfidence.UNAVAILABLE,
        implemented=False,
        proxy_candidates=("daily_return_skewness",),
    ),
    MarketMetricDefinition(
        name="realized_kurtosis",
        family=MetricFamily.VOLATILITY,
        description="Kurtosis of intraday returns.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=78,
        confidence=MetricConfidence.UNAVAILABLE,
        implemented=False,
        proxy_candidates=("daily_return_kurtosis",),
    ),
    MarketMetricDefinition(
        name="intraday_volume_curve",
        family=MetricFamily.INTRADAY_SEASONALITY,
        description="Empirical volume curve from intraday bars.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=130,  # 5+ days of 5-min bars
        confidence=MetricConfidence.UNAVAILABLE,
        implemented=False,
        proxy_candidates=("parametric_u_shape",),
    ),
    MarketMetricDefinition(
        name="lee_mykland_jump",
        family=MetricFamily.JUMP_TAIL_RISK,
        description="Lee-Mykland jump detection from intraday returns.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=78,
        confidence=MetricConfidence.UNAVAILABLE,
        implemented=False,
        proxy_candidates=("cc_rs_jump_proxy",),
        paper_reference="Lee & Mykland (2008), 'Jumps in Financial Markets'",
    ),
    MarketMetricDefinition(
        name="empirical_volume_curve",
        family=MetricFamily.INTRADAY_SEASONALITY,
        description="Empirical intraday volume curve from 5-min bars.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=78,
        confidence=MetricConfidence.UNAVAILABLE,
        implemented=False,
        proxy_candidates=("parametric_u_shape",),
    ),
    # --- Price-action: Fibonacci retracements (5) ---
    MarketMetricDefinition(
        name="fib_382_retrace",
        family=MetricFamily.PRICE_ACTION,
        description="Fibonacci 38.2% retracement level.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="fib_500_retrace",
        family=MetricFamily.PRICE_ACTION,
        description="Fibonacci 50% retracement level.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="fib_618_retrace",
        family=MetricFamily.PRICE_ACTION,
        description="Fibonacci 61.8% retracement level.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="fib_1618_extension",
        family=MetricFamily.PRICE_ACTION,
        description="Fibonacci 161.8% extension level.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="fib_confluence_score",
        family=MetricFamily.PRICE_ACTION,
        description="Confluence score across multiple Fibonacci levels.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),

    # --- Price-action: Bill Williams (7 + alligator 3) ---
    MarketMetricDefinition(
        name="awesome_oscillator",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams Awesome Oscillator.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=5,
        confidence=MetricConfidence.ACTUAL,
    ),
    MarketMetricDefinition(
        name="accelerator_oscillator",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams Accelerator Oscillator.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=7,
        confidence=MetricConfidence.ACTUAL,
    ),
    MarketMetricDefinition(
        name="alligator_jaw",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams Alligator jaw line (blue, period 13).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=13,
        confidence=MetricConfidence.ACTUAL,
    ),
    MarketMetricDefinition(
        name="alligator_teeth",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams Alligator teeth line (red, period 8).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=8,
        confidence=MetricConfidence.ACTUAL,
    ),
    MarketMetricDefinition(
        name="alligator_lips",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams Alligator lips line (green, period 5).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=5,
        confidence=MetricConfidence.ACTUAL,
    ),
    MarketMetricDefinition(
        name="alligator_status",
        family=MetricFamily.PRICE_ACTION,
        description="Alligator phase: sleeping, awakening, eating.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=13,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="williams_fractal_high",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams up fractal (swing high pattern).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high",),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="williams_fractal_low",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams down fractal (swing low pattern).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("low",),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="zone_signal",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams zone signal combining AO/AC signs.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=7,
        confidence=MetricConfidence.PROXY,
    ),

    # --- Price-action: Trend structure (6) ---
    MarketMetricDefinition(
        name="swing_high_n",
        family=MetricFamily.TREND_STRUCTURE,
        description="N-bar swing high detection.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high",),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="swing_low_n",
        family=MetricFamily.TREND_STRUCTURE,
        description="N-bar swing low detection.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("low",),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="hh_hl_pattern",
        family=MetricFamily.TREND_STRUCTURE,
        description="Higher-highs higher-lows bullish trend pattern.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="lh_ll_pattern",
        family=MetricFamily.TREND_STRUCTURE,
        description="Lower-highs lower-lows bearish trend pattern.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="volume_trend_confirmation",
        family=MetricFamily.TREND_STRUCTURE,
        description="Volume-confirmed trend strength.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="trend_phase",
        family=MetricFamily.TREND_STRUCTURE,
        description="Wyckoff trend phase classification.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),

    # --- Price-action: SMC / Smart Money Concepts (11) ---
    MarketMetricDefinition(
        name="bullish_fvg",
        family=MetricFamily.PRICE_ACTION,
        description="Bullish fair value gap (imbalance zone).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=3,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="bearish_fvg",
        family=MetricFamily.PRICE_ACTION,
        description="Bearish fair value gap (imbalance zone).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=3,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="bullish_order_block",
        family=MetricFamily.PRICE_ACTION,
        description="Bullish order block (last down candle before uptrend).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="bearish_order_block",
        family=MetricFamily.PRICE_ACTION,
        description="Bearish order block (last up candle before downtrend).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="breaker_block_bullish",
        family=MetricFamily.PRICE_ACTION,
        description="Bullish breaker block (failed bearish OB reclaimed).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="breaker_block_bearish",
        family=MetricFamily.PRICE_ACTION,
        description="Bearish breaker block (failed bullish OB reclaimed).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="liquidity_sweep_high",
        family=MetricFamily.PRICE_ACTION,
        description="Liquidity sweep above recent swing high.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="liquidity_sweep_low",
        family=MetricFamily.PRICE_ACTION,
        description="Liquidity sweep below recent swing low.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="bos",
        family=MetricFamily.PRICE_ACTION,
        description="Break of structure (trend continuation signal).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="choch",
        family=MetricFamily.PRICE_ACTION,
        description="Change of character (trend reversal signal).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="premium_discount_zone",
        family=MetricFamily.PRICE_ACTION,
        description="SMC premium/discount equilibrium zone classification.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),

    # --- Price-action: VSA signals (10) ---
    MarketMetricDefinition(
        name="no_demand",
        family=MetricFamily.VSA,
        description="VSA no-demand signal: declining volume on up bar.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="no_supply",
        family=MetricFamily.VSA,
        description="VSA no-supply signal: declining volume on down bar.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="stopping_volume",
        family=MetricFamily.VSA,
        description="VSA stopping volume: high volume halting a decline.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="climax_volume",
        family=MetricFamily.VSA,
        description="VSA climax volume: ultra-high volume at market extreme.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="effort_to_rise",
        family=MetricFamily.VSA,
        description="VSA effort to rise: high volume + wide up range.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="effort_to_fall",
        family=MetricFamily.VSA,
        description="VSA effort to fall: high volume + wide down range.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="effort_result_divergence",
        family=MetricFamily.VSA,
        description="VSA effort/result divergence: high volume + small range.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="bag_holding",
        family=MetricFamily.VSA,
        description="VSA bag holding: long upper shadow on high volume.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="shakeout",
        family=MetricFamily.VSA,
        description="VSA shakeout: sudden drop then recovery on high volume.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("low", "close", "volume"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="vsa_test_signal",
        family=MetricFamily.VSA,
        description="VSA test signal: low-volume probe of a support level.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),

    # --- Price-action: Supply/demand zones (8) ---
    MarketMetricDefinition(
        name="demand_zone_low",
        family=MetricFamily.PRICE_ACTION,
        description="Demand zone lower boundary.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="demand_zone_high",
        family=MetricFamily.PRICE_ACTION,
        description="Demand zone upper boundary.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="demand_zone_score",
        family=MetricFamily.PRICE_ACTION,
        description="Demand zone quality score.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="supply_zone_low",
        family=MetricFamily.PRICE_ACTION,
        description="Supply zone lower boundary.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="supply_zone_high",
        family=MetricFamily.PRICE_ACTION,
        description="Supply zone upper boundary.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="supply_zone_score",
        family=MetricFamily.PRICE_ACTION,
        description="Supply zone quality score.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="zone_failure_bullish",
        family=MetricFamily.PRICE_ACTION,
        description="Bullish supply zone failure (price breaks above supply).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="zone_failure_bearish",
        family=MetricFamily.PRICE_ACTION,
        description="Bearish demand zone failure (price breaks below demand).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),

    # --- Price-action: Hurst regime (2) ---
    MarketMetricDefinition(
        name="hurst_exponent",
        family=MetricFamily.PRICE_ACTION,
        description="Hurst exponent for trend persistence vs mean-reversion.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=50,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="fractal_regime",
        family=MetricFamily.PRICE_ACTION,
        description="Fractal-based market regime classification.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=50,
        confidence=MetricConfidence.PROXY,
    ),

    # --- Price-action: Market regime (2) ---
    MarketMetricDefinition(
        name="market_regime",
        family=MetricFamily.PRICE_ACTION,
        description="Market regime classification (trend/range/volatile).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "high", "low", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
    MarketMetricDefinition(
        name="day_type_classification",
        family=MetricFamily.PRICE_ACTION,
        description="Day type classification (trend/up/down/range).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=1,
        confidence=MetricConfidence.PROXY,
    ),

    # --- External provider metrics (21) ---
    # Crypto derivatives — CoinGlass (11)
    MarketMetricDefinition(
        name="funding_rate",
        family=MetricFamily.DERIVATIVES,
        description="Perpetual funding rate from exchange/CoinGlass.",
        required_data_classes=(DataClass.EXTERNAL_PROVIDER,),
        required_providers=("coinglass",),
        min_lookback=1,
        confidence=MetricConfidence.UNAVAILABLE,
    ),
    MarketMetricDefinition(
        name="open_interest",
        family=MetricFamily.DERIVATIVES,
        description="Aggregate open interest from exchange/CoinGlass.",
        required_data_classes=(DataClass.EXTERNAL_PROVIDER,),
        required_providers=("coinglass",),
        min_lookback=1,
        confidence=MetricConfidence.UNAVAILABLE,
    ),
    MarketMetricDefinition(
        name="open_interest_delta_1h",
        family=MetricFamily.DERIVATIVES,
        description="1-hour change in open interest.",
        required_data_classes=(DataClass.EXTERNAL_PROVIDER,),
        required_providers=("coinglass",),
        min_lookback=1,
        confidence=MetricConfidence.UNAVAILABLE,
    ),
    MarketMetricDefinition(
        name="open_interest_delta_24h",
        family=MetricFamily.DERIVATIVES,
        description="24-hour change in open interest.",
        required_data_classes=(DataClass.EXTERNAL_PROVIDER,),
        required_providers=("coinglass",),
        min_lookback=1,
        confidence=MetricConfidence.UNAVAILABLE,
    ),
    MarketMetricDefinition(
        name="cumulative_volume_delta",
        family=MetricFamily.DERIVATIVES,
        description="CVD: cumulative delta between buying and selling volume.",
        required_data_classes=(DataClass.EXTERNAL_PROVIDER,),
        required_providers=("coinglass",),
        min_lookback=1,
        confidence=MetricConfidence.UNAVAILABLE,
    ),
    MarketMetricDefinition(
        name="long_short_ratio",
        family=MetricFamily.DERIVATIVES,
        description="Long/short ratio from exchange/CoinGlass.",
        required_data_classes=(DataClass.EXTERNAL_PROVIDER,),
        required_providers=("coinglass",),
        min_lookback=1,
        confidence=MetricConfidence.UNAVAILABLE,
    ),
    MarketMetricDefinition(
        name="liquidations_long_1h",
        family=MetricFamily.DERIVATIVES,
        description="Long liquidations in the last hour.",
        required_data_classes=(DataClass.EXTERNAL_PROVIDER,),
        required_providers=("coinglass",),
        min_lookback=1,
        confidence=MetricConfidence.UNAVAILABLE,
    ),
    MarketMetricDefinition(
        name="liquidations_short_1h",
        family=MetricFamily.DERIVATIVES,
        description="Short liquidations in the last hour.",
        required_data_classes=(DataClass.EXTERNAL_PROVIDER,),
        required_providers=("coinglass",),
        min_lookback=1,
        confidence=MetricConfidence.UNAVAILABLE,
    ),
    MarketMetricDefinition(
        name="liquidations_long_24h",
        family=MetricFamily.DERIVATIVES,
        description="Long liquidations in the last 24 hours.",
        required_data_classes=(DataClass.EXTERNAL_PROVIDER,),
        required_providers=("coinglass",),
        min_lookback=1,
        confidence=MetricConfidence.UNAVAILABLE,
    ),
    MarketMetricDefinition(
        name="liquidations_short_24h",
        family=MetricFamily.DERIVATIVES,
        description="Short liquidations in the last 24 hours.",
        required_data_classes=(DataClass.EXTERNAL_PROVIDER,),
        required_providers=("coinglass",),
        min_lookback=1,
        confidence=MetricConfidence.UNAVAILABLE,
    ),
    MarketMetricDefinition(
        name="funding_rate_annualised",
        family=MetricFamily.DERIVATIVES,
        description="Annualised funding rate.",
        required_data_classes=(DataClass.EXTERNAL_PROVIDER,),
        required_providers=("coinglass",),
        min_lookback=1,
        confidence=MetricConfidence.UNAVAILABLE,
    ),
    # Equity sentiment / macro (5)
    # Futures / COT (2)
    # Portfolio / cross-asset (3)

    # Elliott Wave (catalogued, not implemented — 5 metrics)
    # trades_and_quotes + classified (2)
    # Level 1 quotes (1)
]

# Conceptual metrics with dual-path resolution


# Conceptual metrics with dual-path resolution
CONCEPTUAL_METRICS: list[MarketMetricDefinition] = [
    MarketMetricDefinition(
        name="volatility",
        family=MetricFamily.VOLATILITY,
        description="Conceptual volatility — auto-selects best path.",
        resolution_paths=(
            MetricResolutionPath(
                metric_name="realized_vol_5m",
                required_data_class=DataClass.INTRADAY_OHLCV,
                required_columns=("close",),
                confidence=MetricConfidence.ACTUAL,
                priority=1,
                interval_min="5min",
            ),
            MetricResolutionPath(
                metric_name="realized_vol_1h",
                required_data_class=DataClass.INTRADAY_OHLCV,
                required_columns=("close",),
                confidence=MetricConfidence.APPROXIMATION,
                priority=2,
                interval_min="1h",
            ),
            MetricResolutionPath(
                metric_name="yang_zhang_vol",
                required_data_class=DataClass.DAILY_OHLCV,
                required_columns=("open", "high", "low", "close"),
                confidence=MetricConfidence.PROXY,
                priority=3,
            ),
        ),
    ),
    MarketMetricDefinition(
        name="spread",
        family=MetricFamily.SPREAD,
        description="Conceptual spread — auto-selects best path.",
        resolution_paths=(
            MetricResolutionPath(
                metric_name="corwin_schultz_spread",
                required_data_class=DataClass.DAILY_OHLCV,
                required_columns=("open", "high", "low", "close"),
                confidence=MetricConfidence.PROXY,
                priority=1,
            ),
            MetricResolutionPath(
                metric_name="roll_spread",
                required_data_class=DataClass.DAILY_OHLCV,
                required_columns=("close",),
                confidence=MetricConfidence.PROXY,
                priority=2,
            ),
        ),
    ),
    MarketMetricDefinition(
        name="jump_detection",
        family=MetricFamily.JUMP_TAIL_RISK,
        description="Conceptual jump detection — auto-selects best path.",
        resolution_paths=(
            MetricResolutionPath(
                metric_name="bipower_variation",
                required_data_class=DataClass.INTRADAY_OHLCV,
                required_columns=("close",),
                confidence=MetricConfidence.ACTUAL,
                priority=1,
                interval_min="5min",
            ),
            MetricResolutionPath(
                metric_name="cc_rs_jump_proxy",
                required_data_class=DataClass.DAILY_OHLCV,
                required_columns=("high", "low"),
                confidence=MetricConfidence.PROXY,
                priority=2,
            ),
        ),
    ),
    MarketMetricDefinition(
        name="intraday_seasonality",
        family=MetricFamily.INTRADAY_SEASONALITY,
        description="Conceptual intraday seasonality — auto-selects best path.",
        resolution_paths=(
            MetricResolutionPath(
                metric_name="empirical_volume_curve",
                required_data_class=DataClass.INTRADAY_OHLCV,
                required_columns=("volume",),
                confidence=MetricConfidence.ACTUAL,
                priority=1,
                interval_min="5min",
            ),
            MetricResolutionPath(
                metric_name="parametric_u_shape",
                required_data_class=DataClass.DAILY_OHLCV,
                required_columns=("volume",),
                confidence=MetricConfidence.PROXY,
                priority=2,
            ),
        ),
    ),
    MarketMetricDefinition(
        name="order_flow_imbalance",
        family=MetricFamily.ORDER_FLOW,
        description="Conceptual order flow imbalance — auto-selects best path.",
        resolution_paths=(
            MetricResolutionPath(
                metric_name="bvc_ofi",
                required_data_class=DataClass.DAILY_OHLCV,
                required_columns=("close", "volume"),
                confidence=MetricConfidence.PROXY,
                priority=1,
            ),
        ),
    ),
    MarketMetricDefinition(
        name="price_impact",
        family=MetricFamily.LIQUIDITY_IMPACT,
        description="Conceptual price impact — auto-selects best path.",
        resolution_paths=(
            MetricResolutionPath(
                metric_name="amihud_illiq",
                required_data_class=DataClass.DAILY_OHLCV,
                required_columns=("close", "volume"),
                confidence=MetricConfidence.PROXY,
                priority=1,
            ),
        ),
    ),
]


