"""Price-action metric definitions — metric definitions shard (data only).

Split from ``_metric_data.py`` by family group to keep each file under the
500-line review threshold. Aggregated by ``_metric_data.py``.
"""

from finbar_strategy_runtime.domain.entities.data_class import DataClass
from finbar_strategy_runtime.domain.entities.market_metric_definition import (
    MarketMetricDefinition,
)
from finbar_strategy_runtime.domain.entities.metric_confidence import MetricConfidence
from finbar_strategy_runtime.domain.entities.metric_family import MetricFamily

METRICS: list[MarketMetricDefinition] = [
MarketMetricDefinition(
        name="fib_382_retrace",
        family=MetricFamily.PRICE_ACTION,
        description="Fibonacci 38.2% retracement level.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="fib_500_retrace",
        family=MetricFamily.PRICE_ACTION,
        description="Fibonacci 50% retracement level.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="fib_618_retrace",
        family=MetricFamily.PRICE_ACTION,
        description="Fibonacci 61.8% retracement level.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="fib_1618_extension",
        family=MetricFamily.PRICE_ACTION,
        description="Fibonacci 161.8% extension level.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="fib_confluence_score",
        family=MetricFamily.PRICE_ACTION,
        description="Confluence score across multiple Fibonacci levels.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="awesome_oscillator",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams Awesome Oscillator.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=5,
        confidence=MetricConfidence.ACTUAL,
    ),
MarketMetricDefinition(
        name="accelerator_oscillator",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams Accelerator Oscillator.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=7,
        confidence=MetricConfidence.ACTUAL,
    ),
MarketMetricDefinition(
        name="alligator_jaw",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams Alligator jaw line (blue, period 13).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=13,
        confidence=MetricConfidence.ACTUAL,
    ),
MarketMetricDefinition(
        name="alligator_teeth",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams Alligator teeth line (red, period 8).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=8,
        confidence=MetricConfidence.ACTUAL,
    ),
MarketMetricDefinition(
        name="alligator_lips",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams Alligator lips line (green, period 5).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=5,
        confidence=MetricConfidence.ACTUAL,
    ),
MarketMetricDefinition(
        name="alligator_status",
        family=MetricFamily.PRICE_ACTION,
        description="Alligator phase: sleeping, awakening, eating.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=13,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="williams_fractal_high",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams up fractal (swing high pattern).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high",),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
        condition_note="May be null on short histories with insufficient swings.",
    ),
MarketMetricDefinition(
        name="williams_fractal_low",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams down fractal (swing low pattern).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("low",),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
        condition_note="May be null on short histories with insufficient swings.",
    ),
MarketMetricDefinition(
        name="zone_signal",
        family=MetricFamily.PRICE_ACTION,
        description="Bill Williams zone signal combining AO/AC signs.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=7,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="swing_high_n",
        family=MetricFamily.TREND_STRUCTURE,
        description="N-bar swing high detection.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high",),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="swing_low_n",
        family=MetricFamily.TREND_STRUCTURE,
        description="N-bar swing low detection.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("low",),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="hh_hl_pattern",
        family=MetricFamily.TREND_STRUCTURE,
        description="Higher-highs higher-lows bullish trend pattern.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="lh_ll_pattern",
        family=MetricFamily.TREND_STRUCTURE,
        description="Lower-highs lower-lows bearish trend pattern.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="volume_trend_confirmation",
        family=MetricFamily.TREND_STRUCTURE,
        description="Volume-confirmed trend strength.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="trend_phase",
        family=MetricFamily.TREND_STRUCTURE,
        description="Wyckoff trend phase classification.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        condition_note=(
            "Returns 'unknown' when no clear phase is detected; fires only "
            "on markup/distribution/accumulation conditions."
        ),
    ),
MarketMetricDefinition(
        name="bullish_fvg",
        family=MetricFamily.PRICE_ACTION,
        description="Bullish fair value gap (imbalance zone).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=3,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="bearish_fvg",
        family=MetricFamily.PRICE_ACTION,
        description="Bearish fair value gap (imbalance zone).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=3,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="bullish_order_block",
        family=MetricFamily.PRICE_ACTION,
        description="Bullish order block (last down candle before uptrend).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="bearish_order_block",
        family=MetricFamily.PRICE_ACTION,
        description="Bearish order block (last up candle before downtrend).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="breaker_block_bullish",
        family=MetricFamily.PRICE_ACTION,
        description="Bullish breaker block (failed bearish OB reclaimed).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="breaker_block_bearish",
        family=MetricFamily.PRICE_ACTION,
        description="Bearish breaker block (failed bullish OB reclaimed).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="liquidity_sweep_high",
        family=MetricFamily.PRICE_ACTION,
        description="Liquidity sweep above recent swing high.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="liquidity_sweep_low",
        family=MetricFamily.PRICE_ACTION,
        description="Liquidity sweep below recent swing low.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="bos",
        family=MetricFamily.PRICE_ACTION,
        description="Break of structure (trend continuation signal).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="choch",
        family=MetricFamily.PRICE_ACTION,
        description="Change of character (trend reversal signal).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="premium_discount_zone",
        family=MetricFamily.PRICE_ACTION,
        description="SMC premium/discount equilibrium zone classification.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="no_demand",
        family=MetricFamily.VSA,
        description="VSA no-demand signal: declining volume on up bar.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="no_supply",
        family=MetricFamily.VSA,
        description="VSA no-supply signal: declining volume on down bar.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="stopping_volume",
        family=MetricFamily.VSA,
        description="VSA stopping volume: high volume halting a decline.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="climax_volume",
        family=MetricFamily.VSA,
        description="VSA climax volume: ultra-high volume at market extreme.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="effort_to_rise",
        family=MetricFamily.VSA,
        description="VSA effort to rise: high volume + wide up range.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="effort_to_fall",
        family=MetricFamily.VSA,
        description="VSA effort to fall: high volume + wide down range.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="effort_result_divergence",
        family=MetricFamily.VSA,
        description="VSA effort/result divergence: high volume + small range.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="bag_holding",
        family=MetricFamily.VSA,
        description="VSA bag holding: long upper shadow on high volume.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=5,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="shakeout",
        family=MetricFamily.VSA,
        description="VSA shakeout: sudden drop then recovery on high volume.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("low", "close", "volume"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="vsa_test_signal",
        family=MetricFamily.VSA,
        description="VSA test signal: low-volume probe of a support level.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="demand_zone_low",
        family=MetricFamily.PRICE_ACTION,
        description="Demand zone lower boundary.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="demand_zone_high",
        family=MetricFamily.PRICE_ACTION,
        description="Demand zone upper boundary.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="demand_zone_score",
        family=MetricFamily.PRICE_ACTION,
        description="Demand zone quality score.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="supply_zone_low",
        family=MetricFamily.PRICE_ACTION,
        description="Supply zone lower boundary.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="supply_zone_high",
        family=MetricFamily.PRICE_ACTION,
        description="Supply zone upper boundary.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="supply_zone_score",
        family=MetricFamily.PRICE_ACTION,
        description="Supply zone quality score.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="zone_failure_bullish",
        family=MetricFamily.PRICE_ACTION,
        description="Bullish supply zone failure (price breaks above supply).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="zone_failure_bearish",
        family=MetricFamily.PRICE_ACTION,
        description="Bearish demand zone failure (price breaks below demand).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=10,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="hurst_exponent",
        family=MetricFamily.PRICE_ACTION,
        description="Hurst exponent for trend persistence vs mean-reversion.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=250,
        confidence=MetricConfidence.PROXY,
        condition_note="Requires at least 250 bars; returns None otherwise.",
    ),
MarketMetricDefinition(
        name="fractal_regime",
        family=MetricFamily.PRICE_ACTION,
        description="Fractal-based market regime classification.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=50,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="market_regime",
        family=MetricFamily.PRICE_ACTION,
        description="Market regime classification (trend/range/volatile).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "high", "low", "volume"),
        min_lookback=220,
        confidence=MetricConfidence.PROXY,
        condition_note="Requires at least 220 bars for classification.",
    ),
MarketMetricDefinition(
        name="day_type_classification",
        family=MetricFamily.PRICE_ACTION,
        description="Day type classification (trend/up/down/range).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=1,
        confidence=MetricConfidence.PROXY,
    ),
]
