"""Volatility & proxy metric definitions — metric definitions shard (data only).

Split from ``_metric_data.py`` by family group to keep each file under the
500-line review threshold. Aggregated by ``_metric_data.py``.
"""

from finbar_strategy_runtime.domain.entities.data_class import DataClass
from finbar_strategy_runtime.domain.entities.market_metric_definition import (
    MarketMetricDefinition,
)
from finbar_strategy_runtime.domain.entities.metric_confidence import MetricConfidence
from finbar_strategy_runtime.domain.entities.metric_family import MetricFamily

METRICS: list[MarketMetricDefinition] = [
MarketMetricDefinition(
        name="close_to_close_vol",
        family=MetricFamily.VOLATILITY,
        description="Naive close-to-close return volatility.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=20,
        confidence=MetricConfidence.ACTUAL,
    ),
MarketMetricDefinition(
        name="parkinson_vol",
        family=MetricFamily.VOLATILITY,
        description="Parkinson high-low range volatility estimator.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Parkinson (1980), 'The Extreme Value Method for Estimating Variance'",
    ),
MarketMetricDefinition(
        name="garman_klass_vol",
        family=MetricFamily.VOLATILITY,
        description="Garman-Klass OHLC volatility estimator.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Garman & Klass (1980), 'On the Estimation of Security Price Volatilities'",
    ),
MarketMetricDefinition(
        name="rogers_satchell_vol",
        family=MetricFamily.VOLATILITY,
        description="Rogers-Satchell OHLC volatility estimator (drift-independent).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Rogers & Satchell (1991), 'Estimating Variance from High, Low and Closing Prices'",
    ),
MarketMetricDefinition(
        name="yang_zhang_vol",
        family=MetricFamily.VOLATILITY,
        description="Yang-Zhang OHLC volatility estimator with overnight gap adjustment.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=21,
        confidence=MetricConfidence.PROXY,
        paper_reference="Yang & Zhang (2000), 'Drift-Independent Volatility Estimation'",
    ),
MarketMetricDefinition(
        name="gk_plus_overnight_vol",
        family=MetricFamily.VOLATILITY,
        description="Garman-Klass with overnight gap component.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="meilijson_vol",
        family=MetricFamily.VOLATILITY,
        description="Meilijson OHLC volatility estimator.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Meilijson (2009), 'A Simple, Fast and Accurate Nonparametric Estimator'",
    ),
MarketMetricDefinition(
        name="daily_return_skewness",
        family=MetricFamily.VOLATILITY,
        description="Rolling skewness of daily returns.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=60,
        confidence=MetricConfidence.ACTUAL,
    ),
MarketMetricDefinition(
        name="daily_return_kurtosis",
        family=MetricFamily.VOLATILITY,
        description="Rolling kurtosis of daily returns.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=60,
        confidence=MetricConfidence.ACTUAL,
    ),
MarketMetricDefinition(
        name="realized_vol_5m",
        family=MetricFamily.VOLATILITY,
        description="Realized volatility from 5-min returns.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=78,  # ~1 day of 5-min bars
        confidence=MetricConfidence.ACTUAL,
        proxy_candidates=("yang_zhang_vol", "parkinson_vol"),
    ),
MarketMetricDefinition(
        name="realized_vol_15m",
        family=MetricFamily.VOLATILITY,
        description="Realized volatility from 15-min returns.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=26,
        confidence=MetricConfidence.ACTUAL,
        proxy_candidates=("yang_zhang_vol", "parkinson_vol"),
    ),
MarketMetricDefinition(
        name="realized_vol_1h",
        family=MetricFamily.VOLATILITY,
        description="Realized volatility from 1-hour returns.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=7,
        confidence=MetricConfidence.ACTUAL,
        proxy_candidates=("yang_zhang_vol", "garman_klass_vol"),
    ),
MarketMetricDefinition(
        name="bipower_variation",
        family=MetricFamily.VOLATILITY,
        description="Bipower variation for jump-robust volatility from intraday returns.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=78,
        confidence=MetricConfidence.ACTUAL,
        proxy_candidates=("cc_rs_jump_proxy",),
        paper_reference="Barndorff-Nielsen & Shephard (2004), 'Power and Bipower Variation'",
    ),
MarketMetricDefinition(
        name="realized_skewness",
        family=MetricFamily.VOLATILITY,
        description="Skewness of intraday returns.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=78,
        confidence=MetricConfidence.ACTUAL,
        proxy_candidates=("daily_return_skewness",),
    ),
MarketMetricDefinition(
        name="realized_kurtosis",
        family=MetricFamily.VOLATILITY,
        description="Kurtosis of intraday returns.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=78,
        confidence=MetricConfidence.ACTUAL,
        proxy_candidates=("daily_return_kurtosis",),
    ),
MarketMetricDefinition(
        name="proxy_atr",
        family=MetricFamily.PROXY,
        description="Wilder RMA ATR (14-period) from high/low/close.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=14,
        confidence=MetricConfidence.PROXY,
        condition_note="Computed from high/low/close; no pandas_ta atr dependency.",
    ),
MarketMetricDefinition(
        name="proxy_vwap",
        family=MetricFamily.PROXY,
        description="VWAP proxy: typical price (H+L+C)/3.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=1,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="proxy_ibs",
        family=MetricFamily.PROXY,
        description="Internal Bar Strength proxy: (C-L)/(H-L).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=1,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="proxy_ib_high",
        family=MetricFamily.PROXY,
        description="Initial Balance high proxy: open + 0.1*ATR.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=14,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="proxy_ib_low",
        family=MetricFamily.PROXY,
        description="Initial Balance low proxy: open - 0.1*ATR.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=14,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="proxy_expected_move",
        family=MetricFamily.PROXY,
        description="Expected daily move proxy: 0.8*ATR.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=14,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="proxy_iv",
        family=MetricFamily.PROXY,
        description="Implied volatility proxy: (ATR/close)*sqrt(252).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=14,
        confidence=MetricConfidence.PROXY,
        condition_note="Annualised ATR% via sqrt(252); returns 0 when close <= 0.",
    ),
MarketMetricDefinition(
        name="proxy_parkinson",
        family=MetricFamily.PROXY,
        description="Parkinson high-low volatility proxy: ln(H/L)^2/(4*ln(2)).",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low"),
        min_lookback=1,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="proxy_garman_klass",
        family=MetricFamily.PROXY,
        description="Garman-Klass OHLC volatility proxy.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=1,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="proxy_rogers_satchell",
        family=MetricFamily.PROXY,
        description="Rogers-Satchell drift-independent volatility proxy.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=1,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="proxy_typical_price",
        family=MetricFamily.PROXY,
        description="VWAP proxy: typical price (H+L+C)/3.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("high", "low", "close"),
        min_lookback=1,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="proxy_ohlc4",
        family=MetricFamily.PROXY,
        description="VWAP proxy with open context: (O+H+L+C)/4.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=1,
        confidence=MetricConfidence.PROXY,
    ),
]
