"""Microstructure metric definitions — metric definitions shard (data only).

Split from ``_metric_data.py`` by family group to keep each file under the
500-line review threshold. Aggregated by ``_metric_data.py``.
"""

from finbar_strategy_runtime.domain.entities.data_class import DataClass
from finbar_strategy_runtime.domain.entities.market_metric_definition import (
    MarketMetricDefinition,
)
from finbar_strategy_runtime.domain.entities.metric_confidence import MetricConfidence
from finbar_strategy_runtime.domain.entities.metric_family import MetricFamily

METRICS: list[MarketMetricDefinition] = [
MarketMetricDefinition(
        name="amihud_illiq",
        family=MetricFamily.LIQUIDITY_IMPACT,
        description="Amihud illiquidity measure: |return| / dollar_volume.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Amihud (2002), 'Illiquidity and Stock Returns'",
    ),
MarketMetricDefinition(
        name="amivest_liquidity",
        family=MetricFamily.LIQUIDITY_IMPACT,
        description="Inverse Amihud — dollar volume per unit price change.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="florackis_lambda",
        family=MetricFamily.LIQUIDITY_IMPACT,
        description="Return-to-volume ratio liquidity measure.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Florackis, Gregoriou & Kostakis (2011), 'Trading Frequency and Asset Pricing'",
    ),
MarketMetricDefinition(
        name="hasbrouck_daily_lambda",
        family=MetricFamily.LIQUIDITY_IMPACT,
        description="Daily price impact proxy from Hasbrouck.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Hasbrouck (2009), 'Trading Costs and Returns for US Equities'",
    ),
MarketMetricDefinition(
        name="liu_illiq",
        family=MetricFamily.LIQUIDITY_IMPACT,
        description="Liu illiquidity: days-with-zero-volume proportion.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("volume",),
        min_lookback=21,
        confidence=MetricConfidence.PROXY,
        paper_reference="Liu (2006), 'A Liquidity-Augmented Capital Asset Pricing Model'",
    ),
MarketMetricDefinition(
        name="bao_pan_zhou_cost",
        family=MetricFamily.LIQUIDITY_IMPACT,
        description="Trading cost proxy from close-to-close return reversal.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
        paper_reference="Bao, Pan & Zhou (2011), 'The Volcker Rule and Market-Making in Times of Stress'",
    ),
MarketMetricDefinition(
        name="signed_sqrt_volume_ofi",
        family=MetricFamily.ORDER_FLOW,
        description="Signed square-root volume order flow imbalance proxy.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="cumulative_signed_volume_ofi",
        family=MetricFamily.ORDER_FLOW,
        description="Cumulative signed volume OFI from BVC classification.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="bvc_buy_volume",
        family=MetricFamily.ORDER_FLOW,
        description="Bulk volume classification estimated buy volume.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="bvc_sell_volume",
        family=MetricFamily.ORDER_FLOW,
        description="Bulk volume classification estimated sell volume.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="bvc_ofi",
        family=MetricFamily.ORDER_FLOW,
        description="Order flow imbalance from bulk volume classification.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="return_volume_correlation",
        family=MetricFamily.ORDER_FLOW,
        description="Rolling correlation between returns and volume.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="daily_vpin",
        family=MetricFamily.INFORMED_TRADING,
        description="Daily volume-synchronized probability of informed trading.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=50,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="spread_based_pin_proxy",
        family=MetricFamily.INFORMED_TRADING,
        description="PIN proxy estimated from spread-based metrics.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="jump_gap_proxy",
        family=MetricFamily.JUMP_TAIL_RISK,
        description="Jump detection from overnight gap in OHLC bars.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="extreme_return_flag",
        family=MetricFamily.JUMP_TAIL_RISK,
        description="Binary flag for extreme returns exceeding a threshold.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="cc_rs_jump_proxy",
        family=MetricFamily.JUMP_TAIL_RISK,
        description="Close-to-close / range-based jump detection proxy.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="overnight_gap_proxy",
        family=MetricFamily.JUMP_TAIL_RISK,
        description="Overnight gap as a jump risk indicator.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="resiliency_autocorr",
        family=MetricFamily.RESILIENCY,
        description="Market resiliency via return autocorrelation.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close",),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="resiliency_spread_to_impact",
        family=MetricFamily.RESILIENCY,
        description="Resiliency from spread-to-price-impact ratio.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="inverse_amihud_resiliency",
        family=MetricFamily.RESILIENCY,
        description="Resiliency from inverse Amihud illiquidity.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("close", "volume"),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="overnight_return",
        family=MetricFamily.INTRADAY_SEASONALITY,
        description="Overnight return component from OHLC decomposition.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=1,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="intraday_return",
        family=MetricFamily.INTRADAY_SEASONALITY,
        description="Intraday return component from OHLC decomposition.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("open", "high", "low", "close"),
        min_lookback=1,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="parametric_u_shape",
        family=MetricFamily.INTRADAY_SEASONALITY,
        description="Parametric U-shaped intraday volume curve proxy.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("volume",),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="first_last_hour_vol_fraction",
        family=MetricFamily.INTRADAY_SEASONALITY,
        description="Fraction of volume in first and last hours of each UTC day.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        required_columns=("volume",),
        min_lookback=24,
        confidence=MetricConfidence.PROXY,
        condition_note=(
            "Intraday only — proxied by grouping bars by UTC date and "
            "summing first/last-hour volume; returns NaN on daily data."
        ),
    ),
MarketMetricDefinition(
        name="volume_to_trade_count_proxy",
        family=MetricFamily.ORDER_ARRIVAL,
        description="Volume divided by trade count proxy.",
        required_data_classes=(DataClass.DAILY_OHLCV, DataClass.INTRADAY_OHLCV),
        required_columns=("volume",),
        min_lookback=20,
        confidence=MetricConfidence.PROXY,
    ),
MarketMetricDefinition(
        name="intraday_volume_curve",
        family=MetricFamily.INTRADAY_SEASONALITY,
        description="Empirical volume curve from intraday bars.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=130,  # 5+ days of 5-min bars
        confidence=MetricConfidence.ACTUAL,
        proxy_candidates=("parametric_u_shape",),
    ),
MarketMetricDefinition(
        name="lee_mykland_jump",
        family=MetricFamily.JUMP_TAIL_RISK,
        description="Lee-Mykland jump detection from intraday returns.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=78,
        confidence=MetricConfidence.ACTUAL,
        proxy_candidates=("cc_rs_jump_proxy",),
        paper_reference="Lee & Mykland (2008), 'Jumps in Financial Markets'",
    ),
MarketMetricDefinition(
        name="empirical_volume_curve",
        family=MetricFamily.INTRADAY_SEASONALITY,
        description="Empirical intraday volume curve from 5-min bars.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        min_lookback=78,
        confidence=MetricConfidence.ACTUAL,
        proxy_candidates=("parametric_u_shape",),
    ),
MarketMetricDefinition(
        name="ib_high",
        family=MetricFamily.SESSION,
        description="Initial Balance high (first-hour range).",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        required_columns=("high", "low"),
        min_lookback=2,
        confidence=MetricConfidence.ACTUAL,
        condition_note="Intraday only — requires session-scoped data to identify first-hour bars.",
    ),
MarketMetricDefinition(
        name="ib_low",
        family=MetricFamily.SESSION,
        description="Initial Balance low (first-hour range).",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        required_columns=("high", "low"),
        min_lookback=2,
        confidence=MetricConfidence.ACTUAL,
        condition_note="Intraday only — requires session-scoped data to identify first-hour bars.",
    ),
MarketMetricDefinition(
        name="ib_midpoint",
        family=MetricFamily.SESSION,
        description="Initial Balance midpoint.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        required_columns=("high", "low"),
        min_lookback=2,
        confidence=MetricConfidence.ACTUAL,
        condition_note="Intraday only — requires session-scoped data to identify first-hour bars.",
    ),
MarketMetricDefinition(
        name="ib_range",
        family=MetricFamily.SESSION,
        description="Initial Balance range width.",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        required_columns=("high", "low"),
        min_lookback=2,
        confidence=MetricConfidence.ACTUAL,
        condition_note="Intraday only — requires session-scoped data to identify first-hour bars.",
    ),
MarketMetricDefinition(
        name="vwap_session",
        family=MetricFamily.SESSION,
        description="Session-scoped cumulative VWAP (resets each calendar day).",
        required_data_classes=(DataClass.INTRADAY_OHLCV,),
        required_columns=("high", "low", "close", "volume"),
        min_lookback=2,
        confidence=MetricConfidence.ACTUAL,
        condition_note="Intraday only — session-scoped VWAP.",
    ),
]
